gText_Birch_Welcome:: @ 82C897B
	.string "Hello there! Pleased to meet you!\n"
	.string "Welcome to the world of POKéMON!\p"
	.string "My name is OAK, but everyone refers\n"
	.string "to me as the POKéMON PROFESSOR.\p"
	.string "$"

gText_Birch_Pokemon:: @ 82C89FB
	.string "This is what a “POKéMON” looks like.\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech:: @ 82C8A1F
	.string "This world is inhabited far and wide\n"
	.string "by creatures called POKéMON.\p"
	.string "Humans and POKéMON coexist\n"
	.string "together, and develop strong bonds.\p"
	.string "Some people play with POKéMON,\n"
	.string "others train them for battle.\p"
	.string "However, there is still so much to\n"
	.string "learn about POKéMON.\p"
	.string "There are many, many secrets\n"
	.string "yet to be unraveled.\p"
	.string "And that's the reason I\n"
	.string "research POKéMON as my profession.\p"
	.string "$"

gText_Birch_AndYouAre:: @ 82C8BD0
	.string "So, tell me about yourself…$"

gText_Birch_BoyOrGirl:: @ 82C8BDD
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName:: @ 82C8BFF
	.string "Now, what name do you go by?$"

gText_Birch_SoItsPlayer:: @ 82C8C1C
	.string "So your name is {PLAYER}{KUN}?$"

gText_Birch_YourePlayer:: @ 82C8C2A
	.string "Ah, I will remember that.\p"
	.string "$"

gText_Birch_AreYouReady:: @ 82C8C7A
	.string "All right!\n"
	.string "{PLAYER}{KUN}, are you ready?\p"
	.string "Your very own tale of grand adventure\n"
	.string "is about to unfold.\p"
	.string "Fun times, difficult times, so many\n"
	.string "experiences await you!\p"
	.string "Let's jump right into the world\n"
	.string "of POKéMON!\p"
	.string "I look forward to seeing you later!\p"
	.string "$"
