Text_PictureBookShelf: @ 82A81E5
	.string "There's a set of POKéMON picture books.$"

Text_BookShelf: @ 82A820D
	.string "It's filled with all sorts of books.$"

Text_PokemonCenterBookShelf: @ 82A8232
	.string "POKéMON magazines!\n"
	.string "POKéMON PAL…\p"
	.string "POKéMON HANDBOOK…\n"
	.string "ADORABLE POKéMON…$"

Text_Vase: @ 82A8276
	.string "This vase looks expensive…\n"
	.string "Peered inside…\p"
	.string "But, it was empty.$"

Text_EmptyTrashCan: @ 82A82B3
	.string "It's empty.$"

Text_ShopShelf: @ 82A82BF
	.string "The shelves brim with all sorts of\n"
	.string "POKéMON merchandise.$"

Text_Blueprint: @ 82A82F7
	.string "A blueprint of some sort?\n"
	.string "It's too complicated!$"

Text_Refrigerator:
	.string "It should be packed with all kinds\n"
	.string "of delicious things to eat.$"

Text_Radio:
	.string "An old radio.\n"
	.string "It's playing nostalgic tunes.$"
	
Text_Dresser:
	.string "It's a nicely made dresser.\n"
	.string "It will hold a lot of stuff.$"

Text_FRLGTV:
	.string "There's a POKéMON on TV!\n"
	.string "It looks like it's having fun.$"
	
Text_Stove:
	.string "It smells delicious!\n"
	.string "Somebody's been cooking here.$"
	
Text_DishCupboard:
	.string "Dishes and plates are neatly\n"
	.string "lined up.$"

Text_Machine:
	.string "Lights in different colors are\n"
	.string "flashing on and off.$"

Text_Phone:
	.string "It's a telephone.\n"
	.string "Better not use it.$"

Text_Computer:
	.string "It's all complicated words and\n"
	.string "numbers that make no sense…$"

Text_Machine2:
	.string "What could this machine be?\n"
	.string "Better not mess around with it!$"
	
Text_Window:	
	.string "My reflection!\n"
	.string "Lookin' good!$"
	
Text_Painting1:	
	.string "It's a pretty picture of a POKéMON.\n"
	.string "It looks like it's feeling good.$"
	
Text_Painting2:	
	.string "My reflection!\n"
	.string "Lookin' good!$"
