EventScript_PictureBookShelf:: @ 82725CE
	msgbox Text_PictureBookShelf, MSGBOX_SIGN
	end

EventScript_BookShelf:: @ 82725D7
	msgbox Text_BookShelf, MSGBOX_SIGN
	end

EventScript_PokemonCenterBookShelf:: @ 82725E0
	msgbox Text_PokemonCenterBookShelf, MSGBOX_SIGN
	end

EventScript_Vase:: @ 82725E9
	msgbox Text_Vase, MSGBOX_SIGN
	end

EventScript_EmptyTrashCan:: @ 82725F2
	msgbox Text_EmptyTrashCan, MSGBOX_SIGN
	end

EventScript_ShopShelf:: @ 82725FB
	msgbox Text_ShopShelf, MSGBOX_SIGN
	end

EventScript_Blueprint:: @ 8272604
	msgbox Text_Blueprint, MSGBOX_SIGN
	end

EventScript_Refrigerator:: 
	msgbox Text_Refrigerator, MSGBOX_SIGN
	end
	
EventScript_Radio:: 
	msgbox Text_Radio, MSGBOX_SIGN
	end
	
EventScript_Dresser:: 
	msgbox Text_Dresser, MSGBOX_SIGN
	end

EventScript_FRLGTV:: 
	msgbox Text_FRLGTV, MSGBOX_SIGN
	end

EventScript_Stove:: 
	msgbox Text_Stove, MSGBOX_SIGN
	end

EventScript_DishCupboard:: 
	msgbox Text_DishCupboard, MSGBOX_SIGN
	end

EventScript_Machine:: 
	msgbox Text_Machine, MSGBOX_SIGN
	end

EventScript_Phone:: 
	msgbox Text_Phone, MSGBOX_SIGN
	end

EventScript_Computer:: 
	msgbox Text_Computer, MSGBOX_SIGN
	end

EventScript_Machine2:: 
	msgbox Text_Machine2, MSGBOX_SIGN
	end

EventScript_Window:: 
	msgbox Text_Window, MSGBOX_SIGN
	end
	
EventScript_Painting1:: 
	msgbox Text_Painting1, MSGBOX_SIGN
	end
	
EventScript_Painting2:: 
	msgbox Text_Painting2, MSGBOX_SIGN
	end