PetalburgCity_House1_MapScripts:: @ 8207799
	.byte 0

PetalburgCity_House1_EventScript_Man:: @ 820779A
	msgbox PetalburgCity_House1_Text_TravelingIsWonderful, MSGBOX_NPC
	end

PetalburgCity_House1_EventScript_Woman:: @ 82077A3
	msgbox PetalburgCity_House1_Text_GoOnAdventure, MSGBOX_NPC
	end

PetalburgCity_House1_Text_TravelingIsWonderful: @ 82077AC
	.string "I heard from big sis that POKéMON won't\n"
	.string "obey a TRAINER they don't respect.\p"
	.string "If you don't have the right GYM BADGES,\n"
	.string "they will just do as they please.$"

PetalburgCity_House1_Text_GoOnAdventure: @ 82077FB
	.string "Sigh…\p"
	.string "I wish I could go on an adventure\n"
	.string "with some POKéMON…\p"
	.string "Crawl through some damp grass…\n"
	.string "Climb rocky, rugged mountains…\p"
	.string "Cross the raging seas…\n"
	.string "Wander about in dark caves…\p"
	.string "And, sometimes, even get a little\n"
	.string "homesick…\p"
	.string "It must be fabulous to travel!$"

