DewfordTown_House4_MapScripts::
	.byte 0


MandarinNorthUncle::
	lock
	faceplayer
	msgbox MandarinNorthUncle_Text_0, MSGBOX_AUTOCLOSE
	release
	end


MandarinNorthUncle_Text_0:
	.string "The WAREHOUSE was sold to a new\nbody not that long ago, and then we\lwere fired by them.\pThe place was then locked up and made\noff-limits, but now there have been\lreports of TEAM ROCKET thugs lurking\laround there.\pI wonder if it is really TEAM ROCKET\nwho acquired the WAREHOUSE?$"
